//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KahBot_v4.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KahBot_v4.Resources.GeneralMessages", typeof(GeneralMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only admins can use this..
        /// </summary>
        internal static string AdminOnly {
            get {
                return ResourceManager.GetString("AdminOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Pm Body.
        /// </summary>
        internal static string AdminPmBody {
            get {
                return ResourceManager.GetString("AdminPmBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Pm Title.
        /// </summary>
        internal static string AdminPmTitle {
            get {
                return ResourceManager.GetString("AdminPmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Pm Body.
        /// </summary>
        internal static string BotPmBody {
            get {
                return ResourceManager.GetString("BotPmBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Pm Custom Field Body.
        /// </summary>
        internal static string BotPmCustomFieldBody {
            get {
                return ResourceManager.GetString("BotPmCustomFieldBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Pm Custom Field Title.
        /// </summary>
        internal static string BotPmCustomFieldTitle {
            get {
                return ResourceManager.GetString("BotPmCustomFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Pm Footer.
        /// </summary>
        internal static string BotPmFooter {
            get {
                return ResourceManager.GetString("BotPmFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Pm Title.
        /// </summary>
        internal static string BotPmTitle {
            get {
                return ResourceManager.GetString("BotPmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the pre-requirements. One or more settings are not filled. Check the GitHub page for requirements: https://github.com/behluluysal/KahBot_v4.
        /// </summary>
        internal static string CheckRequirements {
            get {
                return ResourceManager.GetString("CheckRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountDown Finished.
        /// </summary>
        internal static string CountDownFinished {
            get {
                return ResourceManager.GetString("CountDownFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountDown started for final act! .
        /// </summary>
        internal static string CountDownForFinalActStarted {
            get {
                return ResourceManager.GetString("CountDownForFinalActStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countdown refreshes every 5 second.
        /// </summary>
        internal static string CountDownRefresh5Second {
            get {
                return ResourceManager.GetString("CountDownRefresh5Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countdown refreshes every minute.
        /// </summary>
        internal static string CountDownRefreshMinute {
            get {
                return ResourceManager.GetString("CountDownRefreshMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountDown timer is preparing....
        /// </summary>
        internal static string CountDownTimerPreparing {
            get {
                return ResourceManager.GetString("CountDownTimerPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        internal static string Counter {
            get {
                return ResourceManager.GetString("Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This counter is created by KahBot_v4.
        /// </summary>
        internal static string CounterKahBot {
            get {
                return ResourceManager.GetString("CounterKahBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem at saving data to database.
        /// </summary>
        internal static string DbCrudProblem {
            get {
                return ResourceManager.GetString("DbCrudProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farewell.
        /// </summary>
        internal static string Farewell {
            get {
                return ResourceManager.GetString("Farewell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KahBot FinalAct activated!.
        /// </summary>
        internal static string FinalActActivated {
            get {
                return ResourceManager.GetString("FinalActActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fun Fact: .
        /// </summary>
        internal static string FunFact {
            get {
                return ResourceManager.GetString("FunFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kicked User Counter Title.
        /// </summary>
        internal static string KickedUserCounterTitle {
            get {
                return ResourceManager.GetString("KickedUserCounterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@{0}&gt; named user kicked at {1} by FinalAct command. Farewell!.
        /// </summary>
        internal static string LogChannelLeaveMessage {
            get {
                return ResourceManager.GetString("LogChannelLeaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a future date..
        /// </summary>
        internal static string PastDateError {
            get {
                return ResourceManager.GetString("PastDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason: .
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester: .
        /// </summary>
        internal static string Requester {
            get {
                return ResourceManager.GetString("Requester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your countdown timer request is taken by KahBot_v4.
        /// </summary>
        internal static string RequestTaken {
            get {
                return ResourceManager.GetString("RequestTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date: .
        /// </summary>
        internal static string TargetDate {
            get {
                return ResourceManager.GetString("TargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Left.
        /// </summary>
        internal static string TimeLeft {
            get {
                return ResourceManager.GetString("TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountDown Timer Request Info.
        /// </summary>
        internal static string TimerInfo {
            get {
                return ResourceManager.GetString("TimerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users kicked.
        /// </summary>
        internal static string UsersKicked {
            get {
                return ResourceManager.GetString("UsersKicked", resourceCulture);
            }
        }
    }
}
